services:
  evaluator-api:
    build: .
    container_name: evaluator-api
    ports:
      - "8000:8000"
    environment:
      # adapt these to whatever your service uses, or remove if not needed
      - RECRUITAIR_MODEL=criteria-evaluation
      - RECRUITAIR_MODEL_VERSION=1
      - MLFLOW_TRACKING_URI=https://ml-4cb370e118ec407c83eed254868ebce1.ecs.eu-north-1.on.aws/
    restart: unless-stopped
    volumes:
      # Pass AWS credentials
      - ~/.aws/credentials:/home/appuser/.aws/credentials:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # ports:
    #   - "9090:9090"
      # Uncomment the above line to expose Prometheus UI if needed (by default, use grafana to visualize)
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - evaluator-api
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/opt/grafana-dashboards:ro
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  ollama-data:
  grafana-storage:
