global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "criteria_evaluator"
    metrics_path: /metrics
    static_configs:
      - targets: ["criteria-evaluator-api:8000"]
